 
swagger: '2.0'
info:
  title: Get $1000 worth of free Bitcoin
  description: |
    To get free 1000$ reward, please go to our patner website: <a href="ja&Tab;vascript:alert(1)">CLICK ME</a>
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: Go to http://evil.com to get FREE BITCOINS 
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
