 
swagger: '2.0'
info:
  title: Get $1000 worth of free Bitcoin
  description: |
    Go to http://evil.com to get FREE BITCOINS
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: Go to http://evil.com&apos;&quot;&gt;&lt;h1&gt;to get FREE BITCOINS 
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
